accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$',views.login_view,name="login"),
    url(r'^logout/$',views.logout_view,name="logout")
]

articles/urls.py
from django.conf.urls import url
from . import views

app_name='articles'

urlpatterns = [
    url(r'^$',views.article_list,name="list"),
    url(r'^create/$',views.article_create,name="create"),
    url(r'^(?P<slug>[\w-]+)/$',views.article_detail,name="detail"),
    url(r'^(?P<slug>[\w-]+)/comment/$',views.add_comment,name="add_comment"),

]

myblog/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
from rest_framework.urlpatterns import format_suffix_patterns
from articles import api


urlpatterns = [
    url(r'^$',views.home,name="home"),
    # url(r'^$',article_views.article_list,name="home"),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^articles/',include('articles.urls')),
    url(r'^about/$',views.about,name="about"),
    url(r'^api/articles/$',api.ArticleList.as_view()),
    url(r'^api/articles/(?P<pk>[0-9]+)/$',api.ArticleDetail.as_view())
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += format_suffix_patterns(urlpatterns)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Articles(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png',blank='True')
    author = models.ForeignKey(User,on_delete=models.CASCADE,default=None)



    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:100] + '...'


class Comment(models.Model):
    article = models.ForeignKey('Articles', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

articles/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Articles
        fields = ['title','body','slug','thumb']


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['author','text']

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

def signup_view(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             #  log the user in
             login(request,user)
             return redirect('articles:list')
    else:
        form = UserCreationForm()

    return render(request, 'accounts/signup.html', { 'form': form })


def login_view(request):
    if request.method == 'POST':
         form = AuthenticationForm(data=request.POST)
         if form.is_valid():
             #  log the user in
             user = form.get_user()
             login(request,user)
             if 'next' in request.POST:
                 return redirect(request.POST.get('next'))
             else:
                 return redirect('articles:list')
    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', { 'form': form })


def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render,redirect
from .models import Articles,Comment
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
from articles.config import pagination
from django.shortcuts import get_object_or_404

def article_list(request):
    articles=Articles.objects.all().order_by('date')
    pages=pagination(request,articles,2)

    context={'items':pages[0],
          'page_range':pages[1]
    }

    return render(request,'articles/article_list.html',context)

def article_detail(request,slug):
    #return HttpResponse(slug)
    article=Articles.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':article })


@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method=='POST':
        form=forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author=request.user
            instance.save()            #save it
            return redirect('articles:list')

    else:
        form = forms.CreateArticle()
    return render(request,'articles/article_create.html',{'form':form})



def add_comment(request,slug):
    article = get_object_or_404(Articles,slug=slug)
    if request.method == 'POST':
        form = forms.CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.save()
            return redirect('articles:list')
    else:
        form = forms.CommentForm()
    return render(request,'articles/add_comment.html',{'form':form})

myblog/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render,reverse
def home(request):
    # return HttpResponse('home')
    return HttpResponseRedirect(reverse("articles:list"))
def about(request):
     #return HttpResponse('about')
    return render(request,'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Login</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

articles/templates/articles/add_comment.html
{% extends 'base_layout.html' %}
{% block content %}
     <div class="container">
       <div class="row">
           <div class="col-lg-12">
             <form method="post">
               {% csrf_token %}
             <h1 class="text-center">New comment</h1>
             {{ form.as_p }}
             <button type="submit" class="save btn btn-default">Send</button>
           </form>
           </div>
       </div>
     </div>
{% endblock %}

articles/templates/articles/add_comment_to_article.html
{% extends 'base_layout.html' %}
{% block content %}
<h1>New comment</h1>
 <form action="{% url 'articles:add_comment_to_article' %}" method="post">
     {% csrf_token %}
     {{ form.as_p }}
     <button type="submit" class="save btn btn-default">Send</button>
 </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}
{% block content %}
  <div class="create-article">
    <h2>Create an article</h2>
    <form class="site-form" action="{% url 'articles:create'%}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form}}
      <input type="submit" value="Create">
    </form>

  </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <div class="post-preview article-detail">
        <img  class="pics" src="{{article.thumb.url}}" />


          <h2 class="post-title">
            {{article.title}}
          </h2>

                <p>{{article.body}}</p>
        <p>{{article.date}}</p>
      <!-- Pager -->
      <div class="clearfix">
        <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
  <div class="col-lg-12">
    <hr>
    <a href="{% url 'articles:add_comment' slug=article.slug %}" class="btn btn-default">Add Comment</a>
{% for comment in article.comments.all %}
    <div class="comment">
        <div class="date">{{ comment.created_date }}</div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}
  </div>
  </div>
</div>








{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}
{% block content %}
    <h2 style="text-align:center;margin:20px">New Articles</h2>
    <div class="container">

    <div class="articles">
      <hr>
    {% for article in items %}

       <h3 style="margin:10px"><a href="./{{article.slug}}">{{article.title}}</a></h3>
       <p>{{article.snippet}}</p>
       <p>{{article.date}}</p>
    {% endfor %}
   </div>

 </div>
{% include 'articles/pagination.html' %}

{% endblock %}

articles/templates/articles/pagination.html
{% if items.has_other_pages %}
<div class="text-center">
 <div class="col-6 offset-3 text-center pagination-set">
     <nav aria-label="">
         <ul class="pagination" style="justify-content: center;">
             {% if items.has_previous %}
             <li class="page-item"><a class="page-link" style="background-color: #2c51b7; color: #ff1d18; border: #ff1d18;"
                                      href="?page={{ items.previous_page_number }}">&laquo;</a>
             </li>
             {% else %}
             <li class="page-item disabled"><a class="page-link" style="background-color: #2c51b7; color: #ff1d18; border: #ff1d18;"><span>&laquo;</span></a></li>
             {% endif %}
             {% for i in page_range %}
             {% if items.number == i %}
             <li class="page-item active"><a class="page-link" style="background-color: #ff1d18; border: #ff1d18;" href="#">{{ i }} <span
                     class="sr-only">(current)</span></a></li>
             {% else %}
             <li class="page-item"><a class="page-link" style="background-color: #2c51b7; color: #ffffff; border: #ff1d18;" href="?page={{ i }}">{{ i }}</a></li>
             {% endif %}
             {% endfor %}
             {% if items.has_next %}
             <li class="page-item"><a class="page-link" style="background-color: #2c51b7; color: #ff1d18; border: #ff1d18;" aria-label="Next"
                                      href="?page={{ items.next_page_number }}">&raquo;</a></li>
             {% else %}
             <li class="page-item disabled"><a class="page-link" style="background-color: #2c51b7; color: #ff1d18; border: #ff1d18;"><span>&raquo;</span></a></li>
             {% endif %}
         </ul>
     </nav>
 </div>
</div>
{% endif %}

templates/about.html
{% load static from staticfiles  %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clean Blog - Start Bootstrap Theme</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
      <!-- Bootstrap core CSS -->
      <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
      <!-- Custom fonts for this template -->
      <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet' %}" type="text/css">
      <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
      <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

      <!-- Custom styles for this template -->
      <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home'%}">BLOG-DOM</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home'%}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>


            {% if user.is_authenticated %}
            <li class="nav-item">
              <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token%}
                <button type="submit">Logout</button>
              </form>
            </li>
            <li class="nav-item"><a class="nav-link" href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a></li>
            {% endif %}
          </ul>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static 'img/about-bg.jpg' %}')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
              <h1>About Me</h1>
              <span class="subheading">This is what I do.</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p>
            This is Hrishabh Sharma pursuing Compter Engineering, NIT Surat, currently in first year.
          </p>
          <p>
            This websites app symbolises my chief interest in web developement.
          </p>
         <p>
      Now this web-app serves the function of mediaters for passionate blog writer and curious reader.
       </p>
        </div>
      </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="https://www.facebook.com/hrishabh.sharma.33">
<i class="fab fa-facebook-square"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://github.com/sharma-hrishabh">
<i class="fab fa-github"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://www.linkedin.com/in/hrishabh-sharma-122338163/">
<i class="fab fa-linkedin"></i>
                </a>
              </li>
              <!-- <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li> -->
            </ul>
            <p class="copyright text-muted">Copyright &copy; 2018</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

  </body>

</html>

templates/base_layout.html
{% load static from staticfiles  %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog-Dom</title>
  <link rel="stylesheet" href="{% static 'styles.css' %}">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet' %}" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
  </head>
  <body>
    <!--nav -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home'%}">BLOG-DOM</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home'%}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>

                      {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
            <li class="nav-item">
              <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token%}
                <button class="logout" type="submit">Logout</button>
              </form>
            </li>

            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a></li>
            {% endif %}
          </ul>
          </ul>
        </div>
      </div>
    </nav>
    <!-- header -->
    <header class="masthead" style="background-image: url('{% static 'img/home-bg.jpg' %}')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>Blogging is Fun</h1>
              <span class="subheading">A Blog for all</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    {% block content %}
    {% endblock %}
    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy;2018</p>
          </div>
        </div>
      </div>
    </footer>




    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

  </body>
</html>

templates/homepage.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home</title>
      <link rel="stylesheet" href="{% static 'styles.css' %}">
  </head>
  <body>
    <h3>
    this is home page</h3>
  </body>
</html>